Add support for nested objects in output
upbound/provider-terraform pull request #106
Opened 2023-03-02 21:51 UTC by bdwyertech

### Description of your changes

Add support for nested object output.

Fixes #

I have:

- [ ] Run `make reviewable` to ensure this PR is ready for review.

### How has this code been tested

2023-03-03 12:57 UTC, ytsarev requested changes
Pipes are failing with `go mod tidy` please double check.

2023-03-12 14:47 UTC, bobh66 commented on go.mod
> +	k8s.io/apiextensions-apiserver v0.26.1
This might need to be v0.26.2 now that api/apimachinery/client-go have all been updated

2023-03-12 15:03 UTC, bobh66 requested changes
Needs a rebase and it would be good to include non-sensitive object and list outputs in the output tests to ensure that it works and that nothing breaks it in the future.

2023-03-29 15:09 UTC, Upbound-CLA commented
[![CLA assistant check](https://cla.upbound.io/pull/badge/not_signed)](https://cla.upbound.io/upbound/provider-terraform?pullRequest=106) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.upbound.io/upbound/provider-terraform?pullRequest=106) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.upbound.io/check/upbound/provider-terraform?pullRequest=106) it.</sub>

2023-07-04 18:05 UTC, ytsarev commented
That was an accidental close. @bdwyertech Could you please rebase the PR?

2023-08-10 06:40 UTC, niklasbeinghaus commented
any news on this? I'd like to use list outputs from the provider in a composition without hacks and I guess this is the stuff I'm waiting for...

2023-08-10 12:44 UTC, ytsarev commented on go.mod
> +	k8s.io/apiextensions-apiserver v0.26.1
It seems transitive dependency set/limit 

```
go mod graph | grep apiserver
github.com/upbound/provider-terraform k8s.io/apiextensions-apiserver@v0.26.1
github.com/crossplane/crossplane-runtime@v0.20.0-rc.0.0.20230320143010-c424c4aca5b0 k8s.io/apiextensions-apiserver@v0.26.1
```

2023-08-10 12:53 UTC, ytsarev approved these changes
Thanks a lot for the contribution, @bdwyertech !

Tested it e2e, it looks just great 👍 

```
status:
    atProvider:
      outputs:
        subnet_data:
          arn: arn:aws:ec2:eu-west-1:12345:subnet/subnet-0481765836942e835
          id: subnet-0481765836942e835
        vpc_id: vpc-05d50d36843b95bc3
```

I've extended this PR with the associated example, linter, and pipeline dependency fixes.

@bobh66 as I added my own commits to this PR, can you please take a look before the final merge?

2023-08-10 19:56 UTC, merged