Add support for varmap
upbound/provider-terraform pull request #112
Opened 2023-03-09 05:19 UTC by nakamume

### Description of your changes
Fixes #45

2023-03-09 05:19 UTC, Upbound-CLA commented
[![CLA assistant check](https://cla.upbound.io/pull/badge/not_signed)](https://cla.upbound.io/upbound/provider-terraform?pullRequest=112) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.upbound.io/upbound/provider-terraform?pullRequest=112) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.upbound.io/check/upbound/provider-terraform?pullRequest=112) it.</sub>

2023-03-09 13:06 UTC, bobh66 commented
Hi @nakamume - thanks for the PR.  Can you also update README.md with an example?  Thanks

2023-03-09 21:47 UTC, ytsarev requested changes
Please provide a full description according to PR template with a special focus on the testing part.

2023-03-10 03:59 UTC, nakamume commented on internal/controller/workspace/workspace.go
> +	if p.VarMap != nil {
Done here: https://github.com/upbound/provider-terraform/pull/112/commits/f40accab4c3d98222acfbdaecf828885b35d6111

2023-03-10 04:00 UTC, nakamume commented
@bobh66 @ytsarev - addressed your comments. PTAL

2023-03-11 00:05 UTC, ytsarev approved these changes
Looks great, thanks for the updates!

2023-03-11 22:07 UTC, bobh66 approved these changes
LGTM - thanks!

2023-03-11 23:17 UTC, merged