Improve Terraform Error Output
upbound/provider-terraform pull request #124
Opened 2023-03-14 09:01 UTC by alanjjenkins

An attempt at improving the error output for Terraform by gzipping and base64 encoding the full Terraform error output so as to ensure that nothing is obscured by the provider.

This is an attempt to deal with:

https://github.com/upbound/provider-terraform/issues/37

### Description of your changes

Fixes: #37

I have:

- [x] Run `make reviewable` to ensure this PR is ready for review.

### How has this code been tested

I actually haven't been able to figure out how to test this code properly with how you have your Makefile
setup. Could you please advise on where to put the tests and how to run them with this Makefile?

2023-03-16 09:59 UTC, alanjjenkins commented
Managed to get the code deployed in our cluster and found a few problems that I had to fix.

I now have fixed them and get useful error messages however need to try fix the tests to work again.

2023-03-16 11:11 UTC, alanjjenkins commented
Tests fixed and the code is happily running in our cluster.

2023-03-19 23:18 UTC, ytsarev requested changes
Thanks a lot for the contribution! Could you please check `go mod tidy` and the pipes?

2023-03-20 09:29 UTC, alanjjenkins commented
@ytsarev just sorted out the `go mod tidy` and amended the commit and ran the CI pipeline on my fork and it came back green.

Can you retest your end?

2023-03-20 13:57 UTC, ytsarev commented
@alanjjenkins thanks a lot for the update! Looks all green now from the pipe perspective. I will give it end-to-end test soon on my side before the merge.

2023-03-28 19:29 UTC, mbbush commented
I've been really bashing my head against the wall because of the lack of terraform error details in my compositions. It feels like wearing the wrong glasses prescription: I know the detail is there, I just can't see it!

I'd love it if this could get merged and released sooner rather than later.

2023-03-30 22:23 UTC, ytsarev reviewed
Just tested with intentionally broken Workspace:

```
Status:
  At Provider:
  Conditions:
    Last Transition Time:  2023-03-30T22:15:14Z
    Message:               connect failed: cannot initialize Terraform configuration: Terraform encountered an error. Summary: Unsupported block type. To see the full error run: echo "H4sIAAAAAAAA/1SQwU7kMBBE7/6KUs6rSHOdy0qr5Q+GM3LiCmlhu6N2Z8LAzyMPSMD9VdVTXVYaEY1oWojNdMosDYf4Cl+JWesiz7tFF61/kNhmk4kJE7MeYwiXlbjQLC5q5TeOsjfHRFxjlp5Y1Aip4hKzvH0yTeFr9PCjI1YkOq1IJY5V5hVF057ZEGvqkldJtIZKJrj2CanNY85MYwgPZmpnPNa2b5uad9us8wv8tjEEoKtFqaMvyH3jdA4ATmcYD2+620wM8WhP120eMHR2wHsI/3pLgy73Jgzf+HD/sKqDrxvnPtmfHfFfEm66ozDWHvjC/4bwAQAA//8BAAD//0WCW8x7AQAA" | base64 -d | gunzip
    Reason:                ReconcileError
    Status:                False
    Type:                  Synced
Events:
  Type     Reason                   Age               From                             Message
  ----     ------                   ----              ----                             -------
  Warning  CannotConnectToProvider  9s (x5 over 18s)  managed/workspace.tf.upbound.io  cannot initialize Terraform configuration: Terraform encountered an error. Summary: Unsupported block type. To see the full error run: echo "H4sIAAAAAAAA/1SQwU7kMBBE7/6KUs6rSHOdy0qr5Q+GM3LiCmlhu6N2Z8LAzyMPSMD9VdVTXVYaEY1oWojNdMosDYf4Cl+JWesiz7tFF61/kNhmk4kJE7MeYwiXlbjQLC5q5TeOsjfHRFxjlp5Y1Aip4hKzvH0yTeFr9PCjI1YkOq1IJY5V5hVF057ZEGvqkldJtIZKJrj2CanNY85MYwgPZmpnPNa2b5uad9us8wv8tjEEoKtFqaMvyH3jdA4ATmcYD2+620wM8WhP120eMHR2wHsI/3pLgy73Jgzf+HD/sKqDrxvnPtmfHfFfEm66ozDWHvjC/4bwAQAA//8BAAD//0WCW8x7AQAA" | base64 -d | gunzip
```

```
$ echo "H4sIAAAAAAAA/1SQwU7kMBBE7/6KUs6rSHOdy0qr5Q+GM3LiCmlhu6N2Z8LAzyMPSMD9VdVTXVYaEY1oWojNdMosDYf4Cl+JWesiz7tFF61/kNhmk4kJE7MeYwiXlbjQLC5q5TeOsjfHRFxjlp5Y1Aip4hKzvH0yTeFr9PCjI1YkOq1IJY5V5hVF057ZEGvqkldJtIZKJrj2CanNY85MYwgPZmpnPNa2b5uad9us8wv8tjEEoKtFqaMvyH3jdA4ATmcYD2+620wM8WhP120eMHR2wHsI/3pLgy73Jgzf+HD/sKqDrxvnPtmfHfFfEm66ozDWHvjC/4bwAQAA//8BAAD//0WCW8x7AQAA" | base64 -d | gunzip
There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.

Error: Unsupported block type

  on main.tf line 1:
   1: rewtsource "aws_vpc" "main" {

Blocks of type "rewtsource" are not expected here. Did you mean "resource"?
```

@alanjjenkins This change heavily enhances developer experience with provider-terraform, elegant solution, thank you so much!

2023-03-30 22:23 UTC, ytsarev approved these changes

2023-03-30 22:23 UTC, merged

2023-03-30 22:25 UTC, ytsarev commented
@alanjjenkins @mbbush we plan official provider release batch tomorrow, so this enhancement should be generally available soon

@alanjjenkins if you have a moment, could you please sign the CLA again, our CLA bot had a glitch, sorry for that :)

2023-03-31 06:52 UTC, alanjjenkins commented
> @alanjjenkins @mbbush we plan official provider release batch tomorrow, so this enhancement should be generally available soon
> 
> @alanjjenkins if you have a moment, could you please sign the CLA again, our CLA bot had a glitch, sorry for that :)

Signed again as requested