Terraform Plan Output in Status Field
upbound/provider-terraform pull request #226
Opened 2024-01-05 08:01 UTC by balu-ce

### Description of your changes

This PR is to add the terraform plan output in the status field of crd. This can be integrated with managment polices to apply based on plan

Fixes #223 

I have:

- [x] Run `make reviewable` to ensure this PR is ready for review.

### How has this code been tested

With Local setup as well as been deployed in one of our eks cluster and tested it

2024-01-05 08:01 UTC, Upbound-CLA commented
[![CLA assistant check](https://cla.upbound.io/pull/badge/not_signed)](https://cla.upbound.io/upbound/provider-terraform?pullRequest=226) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.upbound.io/upbound/provider-terraform?pullRequest=226) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.upbound.io/check/upbound/provider-terraform?pullRequest=226) it.</sub>

2024-01-06 02:41 UTC, samof76 commented on internal/terraform/terraform.go
> +	planVal, err := cmd.Output()
Are there chances that `planVal` can be `""` or `nil`? I which case is there a validation for that?

2024-01-06 07:58 UTC, balu-ce commented on internal/terraform/terraform.go
> +	planVal, err := cmd.Output()
There is no way for planval can be nil or empty even if there is no change in plan

2024-01-22 13:00 UTC, ulucinar commented on apis/v1beta1/workspace_types.go
> +	TFPlan   string                       `json:"tfPlan,omitempty"`
We had better use a pointer type here as the field is optional per [Kubernetes API conventions](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#optional-vs-required) and add the `+optional` marker:
```suggestion
	// +optional 
	TFPlan   *string                       `json:"tfPlan,omitempty"`
```

We may also consider marking this field as required but my understanding is that our `tfclient.Diff` implementation always returns a non-zero value for the plan output (either the string `No Change in terraform plan` or the base64-encoded gzipped output from `terraform plan`). But leaving this field optional sounds better to me.

2024-01-22 13:07 UTC, ulucinar commented
Thank you @balu-ce for the PR. I believe the plan output in the status can be beneficial in understanding the modifications to be applied to the external resource, and as described in this PR, it can be used in tandem with the management policies to implement a workflow where the updates to the external resources are first reviewed and then approved (via adding the `Update` management policy).

My biggest concern here is if the plan output contains sensitive information, then we will be exposing it in `status.atProvider`. Do we know whether Terraform can potentially leak sensitive data in the plan output?

2024-01-27 10:32 UTC, ytsarev requested changes
As there are valid concerns around the size of CR and performance / functional issues that it may bring, I suggest we make this functionality optional and controlled by the flag in ProviderConfig.

2024-01-28 06:27 UTC, balu-ce commented
I agree that we can have a flag but cant we just keep it in workspace object itself . Any Specific reason to stop at config level ?

2024-01-29 09:15 UTC, ytsarev commented
@balu-ce you are right, let's keep it in Workspace spec, it will provide more granular control.

2024-01-29 12:52 UTC, balu-ce commented
@ytsarev Please review the PR, added a conditional value under workspace spec

2024-01-30 16:12 UTC, ytsarev commented
/test-examples="examples/workspace-inline-aws.yaml"

2024-01-30 20:46 UTC, negz commented on internal/terraform/terraform.go
> +	formatString := `Terraform Plan. To see the full plan run: echo "%s" | base64 -d | gunzip`
I'd suggest not including this detail in the field. It will make it much more difficult to consume programmatically.

You could always it it back in at the composition layer, if you want to provide human-readable guidance for end users.

2024-01-31 05:57 UTC, balu-ce commented on internal/terraform/terraform.go
> +	formatString := `Terraform Plan. To see the full plan run: echo "%s" | base64 -d | gunzip`
Agree @negz , we faced similar issue on consuming error formatted string, will change it

2024-01-31 05:58 UTC, balu-ce commented
@ytsarev Added in example

2024-01-31 06:49 UTC, negz commented on apis/v1beta1/workspace_types.go
> +	TFPlan   *string                      `json:"tfPlan,omitempty"`
```suggestion
	Plan   *string                      `json:"plan,omitempty"`
```

I think the "TF" is redundant here.

2024-01-31 06:49 UTC, negz commented on apis/v1beta1/workspace_types.go
> +	ShowPlan bool `json:"showPlan"`
This field should be optional, or introducing it will be a breaking change. Optional fields should be pointers with the `omitempty` tag, and the `// +optional` comment.

```suggestion
	// +optional
	ShowPlan *bool `json:"showPlan,omitempty"`
```

Also, is `showPlan` the right name for this field? I would consider `includePlan`. Perhaps subjective, but "Show" feels more like something a CLI would do.

Finally, how confident are you that this field could only ever have two possible states (i.e. show plan or don't show plan)? For example is it possible we'd ever want to include the plan encoded using a different format?


Quoting the [Kubernetes API conventions document](https://github.com/kubernetes/community/blob/4aac5c07b/contributors/devel/sig-architecture/api-conventions.md#primitive-types):

> Think twice about bool fields. Many ideas start as boolean but eventually trend towards a small set of mutually exclusive options. Plan for future expansions by describing the policy options explicitly as a string type alias

2024-01-31 06:49 UTC, negz commented on apis/v1beta1/workspace_types.go
> +	// Variable to show a plan on CR based on condition
```suggestion
	// Include the output of terraform plan in the status.
	// The plan will be gzipped and base64 encoded.
```

This comment will show up as user-facing documentation, so it's important that it clearly describes what the field does and how it works.

2024-01-31 06:52 UTC, balu-ce commented on apis/v1beta1/workspace_types.go
> +	ShowPlan bool `json:"showPlan"`
we cannot make it optional since we need to show plan based on this variable. Also by default bool variable is assigned to false

2024-01-31 06:58 UTC, negz commented
For the record, I'm not convinced that we should do this at all. See https://github.com/upbound/provider-terraform/issues/223#issuecomment-1918499388.

2024-01-31 07:01 UTC, balu-ce commented on apis/v1beta1/workspace_types.go
> +	ShowPlan bool `json:"showPlan"`
I agree that in future there will be more encoding options but still we will be sticking to the conditions. Anyways, if we introduced opinionated encoding options which needs input from the user so we want to introduce new variable

2024-01-31 07:17 UTC, negz commented on apis/v1beta1/workspace_types.go
> +	ShowPlan bool `json:"showPlan"`
> we cannot make it optional since we need to show plan based on this variable.

You can. Treat the field being unset as false.

> I agree that in future there will be more encoding options but still we will be sticking to the condition to show or not. Anyways, if we introduced opinionated encoding options which needs input from the user so we will be introducing new variable

If there will be more encoding options, it would be better to use an enum field than several boolean fields.

2024-01-31 07:39 UTC, balu-ce commented on apis/v1beta1/workspace_types.go
> +	ShowPlan bool `json:"showPlan"`
Then for conditionally showing the plan, we will be checked if the field is set or not. right ?

2024-01-31 19:05 UTC, negz commented on apis/v1beta1/workspace_types.go
> +	ShowPlan bool `json:"showPlan"`
https://pkg.go.dev/k8s.io/utils/ptr#Deref

You can use something like the above:

```go
show := ptr.Deref[bool](mr.Spec.ShowPlan, false)
```

This will return false if the pointer is nil (i.e. unset) or points to a false value. It will return true if the pointer points to a true value.

2024-02-02 05:27 UTC, balu-ce commented on apis/v1beta1/workspace_types.go
> +	ShowPlan bool `json:"showPlan"`
Done @negz

2024-03-26 15:25 UTC, bobh66 reviewed
I can see the value in this but I'm not sure it should be in `status`.  @ytsarev what do you think?  I can really go either way.

2024-03-26 15:25 UTC, bobh66 commented on examples/workspace-inline.yaml
> +    showPlan: true
Should be `includePlan` ?

2024-03-26 20:44 UTC, ytsarev commented
@bobh66 what alternatives to `status` do you have in mind?

2024-03-26 21:05 UTC, bobh66 commented
@ytsarev two possibilities:
- an `Event` with the plan stored in the `message` field
- a `Plan` child resource of the `Workspace`

both have advantages and drawbacks, as does the `status`, and I don't have a good feeling for which is "better"

2024-04-03 09:26 UTC, ytsarev commented
@bobh66  I don't have a preference either:
* the tf plan seems too much for the single `Event` 
* New `Plan` resource seems to be overkilling solution 

`status` to figure out what is happening without getting into the pod seems to be 'good enough'.

 On the other hand, we should probably consolidate this PR with https://github.com/upbound/provider-terraform/pull/248 as there is an intersecting data stream in both.

2024-04-03 09:37 UTC, ytsarev requested changes
@balu-ce 

Thanks a lot for your contribution!

I've performed the manual e2e test of this PR with https://github.com/upbound/provider-terraform/blob/main/examples/workspace-inline-aws.yaml and `spec.forProvider.includePlan: true`

Unfortunately I was not able to see the plan in status apart from `No change in the terraform plan` message:

```
  status:
    atProvider:
      checksum: b1d1f9e12361c1ef23e23c7efd1eccff
      outputs:
        subnet_data:
          arn: arn:aws:ec2:eu-central-1:123456:subnet/subnet-06fa8cd7759bb8832
          id: subnet-06fa8cd7759bb8832
        vpc_id: vpc-0332256723323320a
      tfPlan: No change in the terraform plan
```

Whenever I try to emulate the configuration drift by manually editing Name tag on VPC resource, the Workspace reconciles but at that moment the tfPlan field disappears from the status:

```
  status:
    atProvider:
      outputs:
        subnet_data:
          arn: arn:aws:ec2:eu-central-1:123456:subnet/subnet-06fa8cd7759bb8832
          id: subnet-06fa8cd7759bb8832
        vpc_id: vpc-0332256723323320a
```

After another reconciliation loop it gets back to `tfPlan: No change in the terraform plan`

So effectively I do not see any actional output in this scenario. Am I missing something with my test flow?

Please also squash the commits in this PR as some of them are conflicting with the rebase with `main`

Thanks!

2024-04-03 10:08 UTC, ytsarev commented
@bobh66 after the above e2e experiment - the `Event` actually looks like a better candidate - we could look into the  tf plan data that relates to the previous reconciliation loops

2024-04-03 14:35 UTC, bobh66 commented
Another option would be to converge with #248 and send the data to the pod logs, though I do like the ideal of creating an `Event` when a diff is detected and including the plan output in the `Event`.

2024-05-14 05:37 UTC, balu-ce commented
@ytsarev Have you tried making the management policy to only observe

2024-05-14 13:00 UTC, ytsarev commented
@balu-ce thanks for the clarification. In this case, this flow requires documentation.

2024-05-14 13:12 UTC, balu-ce commented
@ytsarev Yes, Agree.

2024-05-15 10:47 UTC, balu-ce commented
@ytsarev @bobh66 Is there is any plan to bring this feature in next release

2024-10-25 08:49 UTC, balu-ce commented
@bobh66 Any progress on this or we are yet to close.

2025-03-24 08:25 UTC, jeanduplessis commented
@balu-ce Since there isn't alignment from the maintainers on this proposed PR, and we are about to move the source of truth for provider-terraform upstream into crossplane-contrib, I will close this PR for now. Feel free to re-open it upstream or open an issue to discuss the areas of non-alignment of the idea first with the maintainers.

2025-03-24 08:25 UTC, closed without merging