feat: introduce json format for inline module (#165)
upbound/provider-terraform pull request #283
Opened 2024-08-08 12:00 UTC by denniskniep

### Description of your changes
**API Change:**
Added a new property `InlineFormat` to `WorkspaceParameters` which specifies the format of the inline Terraform content. It could be `HCL` or `JSON`

**Change:**
If `InlineFormat` is set to `JSON` the file which is created is named `main.tf.json` instead of `main.tf` 

Fixes #165

I have:
- [x] Run `make reviewable` to ensure this PR is ready for review.

### How has this code been tested
Wrote a UnitTest and already tested it in my environment

2024-08-08 12:00 UTC, Upbound-CLA commented
[![CLA assistant check](https://cla.upbound.io/pull/badge/not_signed)](https://cla.upbound.io/upbound/provider-terraform?pullRequest=283) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.upbound.io/upbound/provider-terraform?pullRequest=283) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.upbound.io/check/upbound/provider-terraform?pullRequest=283) it.</sub>

2024-08-08 16:11 UTC, bobh66 requested changes
Overall I think it looks fine - a couple of comments inline.  Also maybe add an example file to document what the JSON format looks like in the inline module.  Thanks!

2024-08-08 16:11 UTC, bobh66 commented on apis/v1beta1/workspace_types.go
> +// A InlineFormat specifies the format of the inline Terraform content.
This is identical to the VarFileFormat on line 47 - can we combine these so we don't have two definitions of the same string?  Maybe just use FileFormat for both?

2024-08-08 16:11 UTC, bobh66 commented on internal/controller/workspace/workspace.go
> +		filename := tfMain
nit: I think we prefer short variable names, so maybe `fn` or `f` instead of `filename`

2024-08-09 14:00 UTC, denniskniep commented
@bobh66 addressed your review comments

2024-08-24 12:16 UTC, denniskniep commented
@bobh66 can we merge this?

2024-08-26 17:51 UTC, bobh66 approved these changes
Thhanks @denniskniep - LGTM.  It would be nice to have an example `Workspace` that shows the JSON format, but presumably anyone interested in using the JSON format already knows what it looks like.

2024-08-26 17:52 UTC, merged