Add support for varmap
upbound/provider-terraform pull request #75
Opened 2023-02-06 05:58 UTC by bdwyertech

### Description of your changes

Fixes #

I have:

- [ ] Run `make reviewable` to ensure this PR is ready for review.

### How has this code been tested

2023-02-06 05:58 UTC, Upbound-CLA commented
[![CLA assistant check](https://cla.upbound.io/pull/badge/not_signed)](https://cla.upbound.io/upbound/provider-terraform?pullRequest=75) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.upbound.io/upbound/provider-terraform?pullRequest=75) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.upbound.io/check/upbound/provider-terraform?pullRequest=75) it.</sub>

2023-02-08 15:28 UTC, bobh66 commented
@bdwyertech the CI config has been updated, rebasing to the current main should resolve the lint timeout error.

2023-02-08 20:39 UTC, bdwyertech commented
> @bdwyertech the CI config has been updated, rebasing to the current main should resolve the lint timeout error.

Should be good to go @bobh66

2023-02-17 03:06 UTC, nakamume commented
@bdwyertech thanks for the change - this would greatly improve our workflows!

@bobh66 when would this change be released?

2023-02-23 00:18 UTC, ytsarev requested changes
@bdwyertech thank you so much for your contribution, it looks awesome!

As @bobh66 mentioned could you please add an example to https://github.com/upbound/provider-terraform/tree/main/examples and the test for VarMap as in my inline comment?

2023-02-23 00:18 UTC, ytsarev commented on internal/controller/workspace/workspace.go
> +
Can we please write a test for that in https://github.com/upbound/provider-terraform/blob/main/internal/controller/workspace/workspace_test.go ?

2023-03-06 09:03 UTC, nakamume commented
@ytsarev @bdwyertech We are kinda blocked on our Crossplane journey because of this feature. I'd like continue with these changes. I guess, I'll have to fork and open a new PR. Please let me know if there's some way to contribute to this same PR.

2023-03-06 12:47 UTC, ytsarev commented
@nakamume I'm totally open to accepting these changes, we just need to invest in quality and an automated test suite to avoid potential regressions in the future.

2023-03-07 03:16 UTC, nakamume commented
Let me open a new PR then with test coverage

2023-03-09 05:20 UTC, nakamume commented
@ytsarev opened https://github.com/upbound/provider-terraform/pull/112

2023-03-11 23:18 UTC, ytsarev commented
closing in favor of https://github.com/upbound/provider-terraform/pull/112 , thanks a lot for the original implementation! 👍

2023-03-11 23:18 UTC, closed without merging